name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  # You can also trigger this workflow manually or on pull requests, if needed

jobs:
  flaky-test-detection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin' # Adjust the distribution if necessary
        cache: maven

    - name: Clone test repository
      run: |
        cd ~
        git clone https://github.com/vojtechhabarta/typescript-generator
        cd typescript-generator

    - name: Print latest commit
      run: |
        cd ~/typescript-generator
        git rev-parse HEAD

    # Uncomment the next step if you need to checkout a specific commit
    # - name: Checkout specific commit (Optional)
    #   run: |
    #     cd ~/typescript-generator
    #     git checkout <SPECIFIC_COMMIT_HASH>

    - name: Compile the project (skip tests)
      run: |
        cd ~/typescript-generator
        mvn clean install -DskipTests -pl typescript-generator-core -am

    - name: Run the test to check if it passes
      run: |
        cd ~/typescript-generator
        mvn -pl typescript-generator-core test -Dtest=cz.habarta.typescript.generator.TaggedUnionsTest#testTaggedUnionsWithInterfaces

    - name: Run the test with NonDex to check for flakiness
      run: |
        cd ~/typescript-generator
        mvn -pl typescript-generator-core edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=cz.habarta.typescript.generator.TaggedUnionsTest#testTaggedUnionsWithInterfaces
        # Adjust the number of runs with -DnondexRuns=10 or -DnondexRuns=100 if necessary