name: Flaky Test Detection

on:
  push:
    branches: [ "main" ]

jobs:
  flaky-test-detection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Clone test repository
      run: |
        cd ~
        git clone https://github.com/alibaba/Alink
        cd Alink

    - name: Print latest commit
      run: |
        git rev-parse HEAD

    - name: Checkout specific commit
      run: |
        git checkout edb543ee05260a1dd314b11384d918fa1622d9c1

    - name: Compile the project
      run: |
        mvn clean install -DskipTests -pl core -am

    - name: Run the test to check if it passes
      run: |
        mvn -pl core test -Dtest=com.alibaba.alink.operator.common.similarity.dataConverter.MinHashModelDataConverterTest#testMinHash

    - name: Run the test with NonDex to check for flakiness
      run: |
        mvn -pl core edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=com.alibaba.alink.operator.common.similarity.dataConverter.MinHashModelDataConverterTest#testMinHash